# Generated by Django 6.0.7 on 2026-07-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_at']},
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='assessment_result',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
