# Generated by Django 6.0.7 on 2026-07-21 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batchenrollment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='mentorassignment',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_mentors', to='academics.batch'),
        ),
        migrations.AlterField(
            model_name='mentorassignment',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_batches', to='profiles.mentorprofile'),
        ),
        migrations.AddConstraint(
            model_name='batchenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'batch'), name='unique_student_batch_enrollment'),
        ),
    ]
